DROP TABLE IF EXISTS EXAMS CASCADE;
DROP TABLE IF EXISTS STUDENT CASCADE;
DROP TABLE IF EXISTS SUBJ_LECT CASCADE;
DROP TABLE IF EXISTS LECTURER CASCADE;
DROP TABLE IF EXISTS SUBJECT CASCADE;
DROP TABLE IF EXISTS UNIVERSITY CASCADE;
DROP TABLE IF EXISTS EXAM_MARKS CASCADE;
