DROP TABLE IF EXISTS EXAMS;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS SUBJ_LECT;
DROP TABLE IF EXISTS LECTURER;
DROP TABLE IF EXISTS SUBJECT;
DROP TABLE IF EXISTS UNIVERSITY;


CREATE TABLE UNIVERSITY (
  UNIV_ID    SERIAL PRIMARY KEY,
  UNIV_NAME  CHAR(96) NOT NULL UNIQUE,
  RATING     INTEGER,
  CITY       CHAR(20) NOT NULL
);

CREATE TABLE SUBJECT (
   SUBJ_ID     SERIAL PRIMARY KEY,
   SUBJ_NAME   CHAR(32) NOT NULL,
   HOUR        INTEGER,
   SEMESTR     INTEGER
);

CREATE TABLE LECTURER (
  LECTURER_ID SERIAL PRIMARY KEY,
  SURNAME     CHAR(20) NOT NULL,
  NAME        CHAR(20) NOT NULL,
  CITY        CHAR(20) NOT NULL,
  UNIV_ID     INTEGER REFERENCES UNIVERSITY(UNIV_ID)
);

CREATE TABLE SUBJ_LECT (
  LECTURER_ID  INTEGER REFERENCES LECTURER(LECTURER_ID),
  SUBJ_ID      INTEGER REFERENCES SUBJECT(SUBJ_ID)
);

CREATE TABLE STUDENT (
  STUD_ID   SERIAL PRIMARY KEY,
  SURNAME   CHAR(20) NOT NULL,
  NAME      CHAR(20) NOT NULL,
  STIPEND   INTEGER,
  KURS      INTEGER NOT NULL,
  CITY      CHAR(20) NOT NULL,
  BIRTHDAY   DATE,
  UNIV_ID   INTEGER REFERENCES UNIVERSITY(UNIV_ID)
);

CREATE TABLE EXAMS (
  EXAM_ID    SERIAL PRIMARY KEY,
  STUD_ID    INTEGER REFERENCES STUDENT(STUD_ID),
  SUBJ_ID    INTEGER REFERENCES SUBJECT(SUBJ_ID),
  MARK       INTEGER,
  EXAM_DATE  DATE,
  CHECK ((MARK>=2) AND (MARK<=5))
);
